language: python

python:
  - 3.7

install:
  - pip install -r requirements.txt

script:
  - black --check .
  - flake8 .
  - coverage run manage.py test polls

after_script:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: "$ACCESSKEYID"
  secret_access_key: "$SECRETACCESSKEY"
  region: "us-west-2"  
  app: "swe-app1"
  env: "swe-app1-env"
  bucket_name: "elasticbeanstalk-us-west-2-824208337648"
  skip_cleanup: true
  on:
    all_branches: true